name: Go Checks & Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    # Линтинг кода
    - name: Run linter
      run: |
        go install github.com/mgechev/revive@latest
        revive ./...

    # Сборка приложения
    - name: Build
      run: |
        cd cmd/server
        go build -v main.go

    # Запуск юнит-тестов
    - name: Test
      run: |
        cd cmd/server
        go test -v -race ./...